---
# Jenkins Package and version settings
jenkins_version: "2.143"
jenkins_repo_url: deb https://pkg.jenkins.io/debian binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian/jenkins.io.key
jenkins_pkg_url: https://pkg.jenkins.io/debian/binary
jenkins_init_file: /etc/default/jenkins
jenkins_http_port_param: HTTP_PORT
jenkins_java_options_env_var: JAVA_ARGS

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

# Jenkins server settings
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: "{{ hostname }}"
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_ssh_key_name: apcela-devops.pem

# Jenkins plugins settings
jenkins_plugins: [ansible, aws-credentials, bitbucket, email-ext, git, github, mailer, pipeline, ssh-agent, terraform]
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: yes

# Jenkins admin settings
jenkins_admin_username: admin
jenkins_admin_password: Aj}v%D8Ts]
jenkins_admin_password_file: "/var/lib/jenkins/secrets/initialAdminPassword"
jenkins_admin_token: ""
jenkins_admin_token_file: ""

# Jenkins process settings
jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

# Init changes
jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"